- name: install etckeeper
  apt: pkg=etckeeper state=present
  sudo: yes
  notify: initialise etckeeper

- name: configure etckeeper vcs
  lineinfile: dest=/etc/etckeeper/etckeeper.conf
    regexp='^VCS='
    state=present
    line='VCS="{{etckeeper_vcs}}"'
  sudo: yes
