- name: add nginx apt key
  apt_key: data="{{lookup('file', 'nginx_signing.key')}}" state=present
  notify: update apt
  when: nginx_nginx_org_repo

- name: add nginx repo
  apt_repository: state=present repo="{{item}}"
  with_items:
  - "deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx"
  - "deb-src http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx"
  notify: update apt
  when: nginx_nginx_org_repo

- meta: flush_handlers

- name: install software-properties-common
  apt: name=software-properties-common state=present

- name: install nginx
  apt: name=nginx state=present
  notify:
  - create nginx sites-available
  - create nginx sites-enabled
  - disable nginx conf.d includes
  - install default nginx site
  - remove nginx conf.d

- meta: flush_handlers

- name: install nginx custom site confs
  template: >
    dest="/etc/nginx/sites-available/{{item.name}}"
    src="{{item.template}}"
  with_items: nginx_sites
  when: nginx_sites is defined

- name: enable nginx sites
  file: >
    dest="/etc/nginx/sites-enabled/{{ item }}"
    src="/etc/nginx/sites-available/{{ item }}"
    state=link
  with_items: nginx_sites_enabled
  when: nginx_sites_enabled is defined
  notify: reload nginx

- name: disable nginx sites
  file: >
    dest="/etc/nginx/sites-enabled/{{ item }}"
    state=absent
  with_items: nginx_sites_disabled
  when: nginx_sites_disabled is defined
  notify: reload nginx
