# The first run on a new host when we're logging in as root using an SSH key
# will flush handlers at the end of this play and cause sshd to restart
# if we changed ssh access below, after which the rest of the tasks and
# plays will fail because it's no longer possible to ssh in as root.
#
# To continue, just change the ansible ssh user to the user that is allowed
# to ssh in and that has sudo privileges and run the playbook again.

- name: disallow root ssh access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no" state=present
  sudo: yes
  notify: restart ssh

- name: restrict ssh users
  lineinfile: dest=/etc/ssh/sshd_config
    regexp='^#?AllowUsers'
    line='AllowUsers {{ lockdown_ssh_users }}'
    state=present
  when: lockdown_ssh_users is defined
  sudo: yes
  notify: restart ssh

- name: remove sudo group rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent
  sudo: yes

- meta: flush_handlers


