- name: install fail2ban
  apt: pkg=fail2ban
    state=installed
  sudo: yes

- name: create local fail2ban conf
  template: src=jail.local.j2
    dest=/etc/fail2ban/jail.local
  sudo: yes
  notify: restart fail2ban
