- name: create group for user
  group: name="{{ user_group_name }}" gid="{{ user_group_gid }}"

- name: create user
  user: name="{{ user_username }}"
    uid="{{ user_uid }}"
    shell=/bin/bash
    group="{{ user_group_name }}"
    groups="adm"
    password="{{ user_password }}"
    generate_ssh_key=yes

- name: add authorized key for user
  authorized_key:
    user="{{ user_username }}"
    key="{{ user_authorized_key }}"

- name: add user to sudoers
  lineinfile: dest=/etc/sudoers regexp="{{ user_username }} ALL" line="{{ user_username }} ALL=(ALL) NOPASSWD:ALL" state=present
