- name: install logwatch
  apt: pkg=logwatch state=installed
  sudo: yes

- name: conifgure logwatch to email daily
  lineinfile: dest=/etc/cron.daily/00logwatch
    regexp="^/usr/sbin/logwatch"
    line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high"
    state=present
    create=yes
  when: logwatch_email|bool
  sudo: yes
