- name: install git
  apt: pkg=git state=present
  sudo: yes
  notify: git installed

- name: install git-flow
  apt: pkg=git-flow state=present

- name: install git-extras
  apt: pkg=git-extras state=present
