- name: install postfix and mailutils
  apt: pkg={{ item }}
  with_items:
    - postfix
    - mailutils

# TODO: update this later to listen on external interface
- name: configure postfix listen interfaces
  lineinfile: dest=/etc/postfix/main.cf
    regexp='^inet_interfaces '
    line='inet_interfaces = 127.0.0.1'
  notify: restart postfix

- name: configure postfix origin domain
  lineinfile: dest=/etc/mailname
    insertbefore='BOF'
    line='{{ postfix_mailname }}'
    create=yes
  notify: reload postfix

- name: configure postfix mailname
  shell: executable=/bin/bash debconf-set-selections <<< "postfix postfix/mailname string '{{ postfix_mailname }}'"
  notify: reload postfix

- name: configure postfix mailer type
  shell: executable=/bin/bash debconf-set-selections <<< "postfix postfix/main_mailer_type string '{{ postfix_mailer_type }}'"
  notify: reload postfix

# it would be nice to have a module like 'script' that supports template
# variables, which would combine the next two tasks into one task

- name: copy /etc/postfix/main.cf configuration script
  template: src=configure-main.sh
      dest=/var/tmp/postfix-configure-main.sh
      mode=755

- name: run /etc/postfix/main.cf configuration script
  command: /var/tmp/postfix-configure-main.sh
  notify: reload postfix
